cluster.name: "elastic"
node.name: "node-1"

# An alle Interfaces binden
network.host: 0.0.0.0

# Ein-Knoten-Betrieb
discovery.type: single-node

# Render terminiert TLS am Edge; intern HTTP zum Container
# (wenn du End-to-End-TLS willst, unten https aktivieren)
xpack.security.enabled: true

# Optional: HTTP/Transport-Ports explizit (Standard bleibt 9200/9300)
# http.port: 9200
# transport.port: 9300

# Wenn du später E2E-TLS willst:
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/http.key
# xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/http.crt
# xpack.security.http.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca.crt"]