cluster.name: "elastic"
node.name: "node-1"

# An alle Interfaces binden (Render routet extern -> intern)
network.host: 0.0.0.0

# Single-Node
discovery.type: single-node

# Security JA, aber KEIN HTTPS im Container (TLS macht Render am Edge)
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# API-Keys aktivieren
xpack.security.authc.api_key.enabled: true

# (Keine Zertifikats-Pfade setzen, nichts weiter nötig)
# http.port: 9200   # optional, Standard
# transport.port: 9300  # optional, Standard